import asyncpg
import asyncio
import traceback

# URL підключення до Supabase
DATABASE_URL = "postgresql://postgres:2jliJdo8oR73ug08@aws-0-eu-central-1.pooler.supabase.com:6543/postgres"


async def connect_db():
    try:
        conn = await asyncpg.connect(DATABASE_URL)
        print("✅ Successfully connected to Supabase!")
        await conn.close()
    except Exception as e:
        print(f"❌ Database connection error: {e}, {traceback.format_exc()}")


if __name__ == "__main__":

    asyncio.run(connect_db())
